### PR TITLE
fixes #74

### LINKED ISSUE #74: Operator default name not defined
Small MFE demonstrating that `Operator` without `name=` cannot be passed to `apply`

```
using Devito, Test, PyCall, Printf

grid1 = Devito.Grid(shape=(2,2), origin=(0,0), extent=(1,1), dtype=Float32)
f = Devito.Function(name="f", grid=grid1, space_order=4)

# works
apply(Operator([Eq(f, 1)], name="op"))

# fails
apply(Operator([Eq(f, 1)]))
```

### PR DESCRIPTION
**Pull request by samtkaplan**
closes #74

### CODE REVIEW

File: src/Devito.jl [hunk 1]
```diff
@@ -433,6 +433,21 @@ end
...
+            new(pycall(devito.Operator, PyObject, args...; kwargs...))
+        else
+            new(pycall(devito.Operator, PyObject, args...; name="Kernel", kwargs...))
+        end
+    end
+end
+PyCall.PyObject(x::Operator) = x.o
+Base.convert(::Type{Operator}, x::PyObject) = Operator(x)
+export Operator
+
```
Comment (deckerla) [inline src/Devito.jl:450]:
```suggestion

"""
    Operator(expressions...; kwargs)
Generate, JIT-compile and run C code starting from an ordered sequence of symbolic expressions.
Parameters:
    expressions (expr-like or list or expr-like) - The (list of) expression(s) defining the Operator computation.

    **kwargs:

        name::String
        Name of the Operator, defaults to “Kernel”.

        subs::Dict
        Symbolic substitutions to be applied to expressions.

        opt::String
        The performance optimization level. Defaults to configuration["opt"].

        language::String
        The target language for shared-memory parallelism. Defaults to configuration["language"].

        platform::String
        The architecture the code is generated for. Defaults to configuration["platform"].

        compiler::String
        The backend compiler used to jit-compile the generated code. Defaults to configuration["compiler"].
"""
function Operator End
```

File: test/serialtests.jl [hunk 2]
```diff
@@ -785,3 +785,13 @@ end
...
 
+@testset "Operator default naming" begin
+    grid1 = Devito.Grid(shape=(2,2), origin=(0,0), extent=(1,1), dtype=Float32)
+    f = Devito.Function(name="f", grid=grid1, space_order=4)
+
+    op = Operator([Eq(f,1)]; name="foo")
+    @test name(op) == "foo"
+    op = Operator([Eq(f,1)])
+    @test name(op) == "Kernel"
+end
```
Comment (deckerla) [inline test/serialtests.jl:796]:
```suggestion
op = Operator(Eq(f,1))
@test name(op) == "Kernel"
op = Operator( (Eq(f,1), Eq(f,1)))
@test name(op) == "Kernel"
op = Operator( [Eq(f,1), Eq(f,1)])
@test name(op) == "Kernel"
op = Operator(Eq(f,1), opt="advanced")
@test name(op) == "Kernel"
op = Operator( (Eq(f,1), Eq(f,1)), opt="advanced")
@test name(op) == "Kernel"
op = Operator( [Eq(f,1), Eq(f,1)], opt="advanced")
@test name(op) == "Kernel"

end
```

**Review by deckerla — CHANGES_REQUESTED** [review]
What do you think of the proposed documentation, and adding tests to make sure operator construction works with Equations, tuples of Equations, Arrays of Equations, and keyword arguments supplied?

**Review by deckerla — APPROVED** [review]
